version: '3.7'

services:
  postgresql:
    image: postgres:12-alpine
    restart: unless-stopped
    ports:
      - 5434:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Darisae12
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local